env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    from_secret: gcp-credentials
    build_command: python3.8 -m pip install -r requirements.txt
    start_command: python3.8 app.py  # This specifies how to start your Flask app
  - name: PORT
    value: 8080
  - name: BUCKET_NAME
    value: bi_lstm_model  # Replace with your GCS bucket name
  - name: MODEL_BLOB_NAME
    value: model.h5  # Replace with the path within the bucket where the model is located
